# bootstrap-theme
# https://github.com/benTheBike/bootstrap-theme

# Bootstrap theme (leave blank for default)
# Use a link to a (preferably minified) bootstrap-theme.css. I recommend looking @ https://bootswatch.com
bs_theme:

# Color for <meta> theme-color
theme_color:

# Path to favicon. /source/ is considered the root folder
favicon_path: img/favicon.ico

# Navbar links. Formatting ex:
# Blog: /blog
navbar_links:
  Home: /
  Blog: /blog
  Code: /code
  About: /about